version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=1234
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - db:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
  app:
    depends_on:
      - mysqldb
    build: ./app
    restart: on-failure
    ports:
      - 6868:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/correios?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "1234",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.
    stdin_open: true
    tty: true

volumes:
  db: